### ISSUE TITLE
Image Writer: two-channel images

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#160]
When I try to write a two-channel PNG / JPEG image with the new image writer, I expected to get the same image written as displayed (red / green). Instead, only the first channel is written black/white.

The old image writer didn't produce any readable result.

**Comment by maierl** [comment]
tested with an artificial third channel (hoping rgb images would be fine), but still only first channel gets written.

**Comment by dietzc** [comment]
@gab1one any news on this?

**Comment by gab1one** [comment]
I can confirm this bug, no idea what is causing it though yet.

**Comment by gab1one** [comment]
As this seems to be an upstream problem we need more time to fix it.

**Comment by maierl** [comment]
any update?

**Comment by maierl** [comment]
anything new here?

**Comment by maierl** [comment]
more generally, any PNG file is only written black-and-white, probably its red channel. Tested this time with Labelling to RGB Img as input.

**Comment by imagejan** [comment]
For the time being, you can work around it by using the _Labeling to PNG Images_ node and the _Image Column Writer_, no?
But I agree it would be nice to have possibilities to configure how multi-channel images are written (as RGB, multi-page, with LUTs etc.)

**Comment by maierl** [comment]
thanks @imagejan, you're right about the workaround.

**Comment by maierl** [comment]
well, with that workaround, the offsets of the labelings seem wrong. but I'm not going into this now.

**Comment by dietzc** [comment]
how can they be wrong?

**Comment by maierl** [comment]
never mind, that was a wrong assumption that I had.

**Comment by beschu** [comment]
I created a workflow (named: multi-channel-images-issue160) and placed it on merkur. It checks for this bug and some other stuff i encountered:

- Sometimes it appears that a source does not get set.
- Sometimes  axis 2 is named "Time" instead of "Channel" after a Write and then a Re-Read.

- If there is a transparent part in a png, a Write-and-Re-Read will cause the colors to be messed up.

- If there is no transparent part in the png and the above listed problems don't occur everything seems to be fine here (using Gnome Ubuntu). Reading a .png, writing it and rereading afterwards works as intended.

**Comment by tibuch** [comment]
@beschu could you create individual issues and link them?

**Comment by beschu** [comment]
@tibuch  I created the issues and linked them here. I also linked from those issues to this issue as reference.

**Comment by gab1one** [comment]
👍
