### ISSUE TITLE
Problem when joining labeling source with labeling on LINUX

### ISSUE THREAD

**Issue by Fritze** [knime-ip/knip#196]
Hi again,

I have a problem joining a labeling with its respective labeling source. One of the two inputs contains three rows (see input1_joiner.png). 

Using KNIME locally on my windows PC, everything works just fine and the joiner gives out a table containing three rows, as expected with the inner join (KNIME 2.12.0, KNIP 1.3.0.201508111623 ). Testing the same workflow on Linux ( KNIME 2.12.1, latest KNIP nightly ) the joiner produces an output with 15 rows (see output_joiner.png), although "inner join" was selected as before (settings_joiner.png). To me, his looks like a problem since the joiner node behaves differently in Windows and Linux.
I've attached an example workflow. Unfortunately, once saved as a seperate table, I was not able to open the input to test it on the example workflow (Error: Cannot read image, see workflow attached).
This is why included the screenshots to show the settings/input/output that created the original error.

https://powerfolder.dkfz.de/dl/fiJ36QChcTVTisHNLnNJkKAt/joiner_broken.zip

Best,
Friedrich

**Comment by dietzc** [comment]
Hi Friedrich, 

I have very, very, very strong doubts that the `Joiner` behaves different on Linux/Windows, as this node is tested by over 100k users world-wide. Rather something with the image source might have changed, as the image source corresponds to the file path of your image. Potentially, you try to join a labeling with another labeling (join works on sources), which have different file paths.

Anyway, the "Cannot read image" should never happen. I will take a look.

Thanks for reporting this!

Christian

**Comment by dietzc** [comment]
Hi @Fritze,

as already mentoined, the `Joiner` should work as expected. Which output is expected? If it would be a joiner bug, the problem should be independend of images and reproducible with the `Data Generator`.

The other problem, where you saved images, which can't be read in anymore: Is this problem reproducible with your workflow? It's really hard to debug, as I don't know what's going on before. So if the problem is reproducible on your side, I would be happy to see the workflow and learn how to reproduce it.

**Comment by dietzc** [comment]
seems to be obsolete
