### ISSUE TITLE
Improve Labeling to RGB Image Node usability

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip#301]
The Labeling to RGB Image node needs some love, resulting in the following UI improvements.

- [x] Node complains (red signal light) if no Labelings are available in the input table.
- [ ] ~~Column suffix model should only be active when append is selected.~~

**Comment by beschu** [comment]
Column suffix model should only be disabled for the Replace Column Creation Mode.

**Comment by tibuch** [comment]
Right now a suffix can be added in every Column Creation Mode and I would not change that for now.

The problem with this enhancement is, that we have to check all KNIP nodes again because not every node is based on the same classes. If we want to change this behaviour we should change it in KNIP 2.0.

**Comment by tibuch** [comment]
The suffix behaviour will be fixed with KNIP 2.0. See https://github.com/knime-ip/knip/issues/360.

**Comment by beschu** [comment]
Added the functionality that now the nodes that use ValueToCellNodeModel will complain if no columns of correct type are available.
