### ISSUE TITLE
Image Viewer: Label Options partially hidden when in multiple view

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#356]
When opening multiple images in combined view, the Label Options (particularly the transparency setting) are partially hidden and inaccessible.
See screenshot:
![label_options_hidden](https://cloud.githubusercontent.com/assets/2033938/16340998/3c9f4df2-3a2b-11e6-914f-1d8fffc6882b.png)

**Comment by AndreasBurger** [comment]
I've fixed the Layout bug, but there is currently no transparency option in the combined view due to the way the renderer handles transparency. I'll talk to @dietzc about enabling it for labelings/images.

**Comment by AndreasBurger** [comment]
I've added the transparency slider to the section of the Viewer concerned with all displayed images since the slider affects all rendered images at the same time.

Currently, the RenderUnit draws the first active image as solid image and blends all further images into this "background" using the selected transparency. For a future relase it'd be nice if the transparency setting works per image instead of globally.
