### ISSUE TITLE
Enlarge Segments

### ISSUE THREAD

**Issue by tibuch** [knime-ip/knip#442]
Enlarge Segments takes every segment of a Labeling and enlarges it by a given number of pixels.

This is different from labeling resizing. If we enlarge a segment, the distance from the new segment border to the old segment border is always the given number of pixels. 

![image](https://cloud.githubusercontent.com/assets/5450869/21936608/18971328-d9b2-11e6-808e-4b8be12a73ac.png)

I have created a Wrapped Metanode ([enlarge_labels.zip](https://github.com/knime-ip/knip/files/704758/enlarge_labels.zip)) (with a Java Snippet Node inside) which generates such a Labeling.

**Comment by dietzc** [comment]
Oh, wow. Great job building this workflow. However, the top-part seems to be a bit messy? Can't you put the entire top-part of the workflow (dimension extraction etc) inside the java-snippet?

**Comment by imagejan** [comment]
Thanks for the illustrative Java Snippet example!

I know the issue is about creating a new node, but I have some questions/comments anyways regarding the example Metanode:

* The _Variable To Table Row_ node is redundant, because the workflow already contains that variable at that stage.
* Why don't you use a sequence of _Labeling Filter_ and _Morphological Labeling Operations_ with a 2D disk-shaped structuring element (looping over each single label to allow overlap)? Performance reasons only, or something else to consider?

**Comment by tibuch** [comment]
@imagejan _Morphological Labeling Operations_ works like a charm with a disk-shaped structuring element. I just forgot the option which allows a custom structuring element. Thanks for pointing it out!

Here is the new version: [growing_labels.zip](https://github.com/knime-ip/knip/files/708250/growing_labels.zip)

Is there a simpler way to create a disk of a certain size? Only way I know is _Java Snippet_.

**Comment by imagejan** [comment]
> Is there a simpler way to create a disk of a certain size?

There is the _Structuring Element Creator_ that lets you create spheres and boxes of arbitrary size, in any number of dimensions :-)

----

Fun fact (or bug report?): when opening you workflow, executing the Interactive Segmentation View, then looking at the Outport of the Image Generator -> it contains a white circle, whereas it should be all black! (tested on Windows)
Can you reproduce? Is this due to your use of the Java Snippet?
It also happens when I execute the Java Snippet without previously executing the Generator, but not when executing the Generator explicitly...

**Comment by tibuch** [comment]
Oh right! :blush: Thanks again @imagejan 
----
I can reproduce this. I guess it is due to the fact that I write directly to the input image in my java-snippet. Which is not best practice.
